parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    MccApiTools\RequestObjectBundle\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Model,Utils}'
